/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;

import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import vendingmachine.models.SnackMachine;

/**
 *
 * @author rawan
 */
public class JFrameVendingMachine extends javax.swing.JFrame {
    /**
     *Create new SnackMachine Object
     */
    public SnackMachine snackMachine = new SnackMachine();
    
    
    /**
     * Creates new form JFrameVendingMachine
     */
    public JFrameVendingMachine() {   
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moneySlot_jPanel = new javax.swing.JPanel();
        coin_jTextField = new javax.swing.JTextField();
        change_jButton2 = new javax.swing.JButton();
        jButton_10c = new javax.swing.JButton();
        jButton_20c = new javax.swing.JButton();
        jButton_50c = new javax.swing.JButton();
        jButton_20$ = new javax.swing.JButton();
        jButton_1$ = new javax.swing.JButton();
        jButton_50$ = new javax.swing.JButton();
        keyPaid_jPanel2 = new javax.swing.JPanel();
        keyPaid_jTextField = new javax.swing.JTextField();
        jButton_8 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        ok_jButton3 = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        snackSlots_jPanel1 = new javax.swing.JPanel();
        jLabel0_2 = new javax.swing.JLabel();
        jLabel1_0 = new javax.swing.JLabel();
        jLabel0_4 = new javax.swing.JLabel();
        jLabel0_5 = new javax.swing.JLabel();
        jLabel0_6 = new javax.swing.JLabel();
        jLabel0_7 = new javax.swing.JLabel();
        jLabel0_9 = new javax.swing.JLabel();
        jLabel0_0 = new javax.swing.JLabel();
        jLabel0_11 = new javax.swing.JLabel();
        jLabel0_1 = new javax.swing.JLabel();
        jLabel0_12 = new javax.swing.JLabel();
        jLabel0_13 = new javax.swing.JLabel();
        jLabel0_14 = new javax.swing.JLabel();
        jLabel0_15 = new javax.swing.JLabel();
        jLabel0_16 = new javax.swing.JLabel();
        jLabel0_17 = new javax.swing.JLabel();
        jLabel0_18 = new javax.swing.JLabel();
        jLabel0_19 = new javax.swing.JLabel();
        jLabel0_20 = new javax.swing.JLabel();
        jLabel0_21 = new javax.swing.JLabel();
        jLabel0_22 = new javax.swing.JLabel();
        jLabel0_23 = new javax.swing.JLabel();
        jLabel0_24 = new javax.swing.JLabel();
        jLabel0_25 = new javax.swing.JLabel();
        jLabel0_26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        title_Label1 = new javax.swing.JLabel();
        jPanel1_ErrorMessage = new javax.swing.JPanel();
        jLabel_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVALID KEY PAID");

        moneySlot_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Money Slots"));

        coin_jTextField.setEditable(false);
        coin_jTextField.setText("$ 0.00");
        coin_jTextField.setToolTipText("");
        coin_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin_jTextFieldActionPerformed(evt);
            }
        });

        change_jButton2.setText("Change");
        change_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_jButton2ActionPerformed(evt);
            }
        });

        jButton_10c.setText("10c");
        jButton_10c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_10cActionPerformed(evt);
            }
        });

        jButton_20c.setText("20c");
        jButton_20c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_20cActionPerformed(evt);
            }
        });

        jButton_50c.setText("50c");
        jButton_50c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_50cActionPerformed(evt);
            }
        });

        jButton_20$.setText("20$");
        jButton_20$.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_20$ActionPerformed(evt);
            }
        });

        jButton_1$.setText("1$");
        jButton_1$.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1$ActionPerformed(evt);
            }
        });

        jButton_50$.setText("50$");
        jButton_50$.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_50$ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moneySlot_jPanelLayout = new javax.swing.GroupLayout(moneySlot_jPanel);
        moneySlot_jPanel.setLayout(moneySlot_jPanelLayout);
        moneySlot_jPanelLayout.setHorizontalGroup(
            moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moneySlot_jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moneySlot_jPanelLayout.createSequentialGroup()
                        .addComponent(coin_jTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(change_jButton2))
                    .addGroup(moneySlot_jPanelLayout.createSequentialGroup()
                        .addGroup(moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_10c, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jButton_1$, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(moneySlot_jPanelLayout.createSequentialGroup()
                                .addComponent(jButton_20c, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_50c, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(moneySlot_jPanelLayout.createSequentialGroup()
                                .addComponent(jButton_20$, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_50$, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
        );
        moneySlot_jPanelLayout.setVerticalGroup(
            moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moneySlot_jPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coin_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_10c)
                    .addComponent(jButton_20c)
                    .addComponent(jButton_50c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneySlot_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_1$)
                    .addComponent(jButton_20$)
                    .addComponent(jButton_50$))
                .addContainerGap())
        );

        keyPaid_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Key Paid"));

        keyPaid_jTextField.setEditable(false);
        keyPaid_jTextField.setToolTipText("");
        keyPaid_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyPaid_jTextFieldActionPerformed(evt);
            }
        });

        jButton_8.setText("8");
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });

        jButton_6.setText("6");
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });

        jButton_9.setText("9");
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });

        jButton_5.setText("5");
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton_4.setText("4");
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_3.setText("3");
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_7.setText("7");
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });

        jButton_2.setText("2");
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_1.setText("1");
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_0.setText("0");
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });

        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        ok_jButton3.setText("OK");
        ok_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_jButton3ActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout keyPaid_jPanel2Layout = new javax.swing.GroupLayout(keyPaid_jPanel2);
        keyPaid_jPanel2.setLayout(keyPaid_jPanel2Layout);
        keyPaid_jPanel2Layout.setHorizontalGroup(
            keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyPaid_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keyPaid_jPanel2Layout.createSequentialGroup()
                        .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jButton_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ok_jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jButton_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(keyPaid_jPanel2Layout.createSequentialGroup()
                        .addComponent(keyPaid_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Cancel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        keyPaid_jPanel2Layout.setVerticalGroup(
            keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyPaid_jPanel2Layout.createSequentialGroup()
                .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyPaid_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_8)
                    .addComponent(jButton_9)
                    .addComponent(jButton_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_6)
                    .addComponent(jButton_4)
                    .addComponent(jButton_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_3)
                    .addComponent(jButton_2)
                    .addComponent(jButton_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keyPaid_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_0)
                    .addComponent(jButton_clear)
                    .addComponent(ok_jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        snackSlots_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Snack Slots"));

        jLabel0_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_2.setText("ID: 2");
        jLabel0_2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_0.setText("ID: 6");
        jLabel1_0.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_4.setText("ID: 12");
        jLabel0_4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_5.setText("ID: 17");
        jLabel0_5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_6.setText("ID: 11");
        jLabel0_6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_7.setText("ID: 21");
        jLabel0_7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_9.setText("ID: 16");
        jLabel0_9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_0.setText("ID: 1");
        jLabel0_0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel0_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel0_0.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel0_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_11.setText("ID: 7");
        jLabel0_11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_1.setText("ID: 8");
        jLabel0_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_12.setText("ID: 13");
        jLabel0_12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_13.setText("ID: 18");
        jLabel0_13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_14.setText("ID: 23");
        jLabel0_14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_15.setText("ID: 4");
        jLabel0_15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_16.setText("ID: 3");
        jLabel0_16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_17.setText("ID: 14");
        jLabel0_17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_18.setText("ID: 24");
        jLabel0_18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_19.setText("ID: 19");
        jLabel0_19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_20.setText("ID: 5");
        jLabel0_20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_21.setText("ID: 10");
        jLabel0_21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_22.setText("ID: 15");
        jLabel0_22.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_23.setText("ID: 25");
        jLabel0_23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_24.setText("ID: 20");
        jLabel0_24.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_25.setText("ID: 22");
        jLabel0_25.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel0_26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0_26.setText("ID: 9");
        jLabel0_26.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Item1: $0.20");

        jLabel2.setText("Item2: $0.10");

        jLabel3.setText("Item3: $1.00");

        jLabel4.setText("Item4: $0.50");

        jLabel5.setText("Item5: $0.30");

        jLabel6.setText("Item21: $4.00");

        jLabel7.setText("Item22: $3.50");

        jLabel8.setText("Item23: $3.00");

        jLabel9.setText("Item24: $2.50");

        jLabel10.setText("Item25: $2.00");

        jLabel11.setText("Item16: $3.00");

        jLabel12.setText("Item17: $3.10");

        jLabel13.setText("Item18: $3.20");

        jLabel14.setText("Item19: $3.10");

        jLabel15.setText("Item21: $3.00");

        jLabel16.setText("Item11: $2.10");

        jLabel17.setText("Item12: $2.20");

        jLabel18.setText("Item13: $2.30");

        jLabel19.setText("Item14: $2.40");

        jLabel20.setText("Item15: $2.70");

        jLabel21.setText("Item6: $1.00");

        jLabel22.setText("Item7: $1.50");

        jLabel23.setText("Item8: $1.20");

        jLabel24.setText("Item9: $1.10");

        jLabel25.setText("Item10: $1.80");

        title_Label1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        title_Label1.setText("SNACK VENDING MACHINE ");

        javax.swing.GroupLayout snackSlots_jPanel1Layout = new javax.swing.GroupLayout(snackSlots_jPanel1);
        snackSlots_jPanel1.setLayout(snackSlots_jPanel1Layout);
        snackSlots_jPanel1Layout.setHorizontalGroup(
            snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel0_11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                            .addComponent(jLabel0_26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                            .addComponent(jLabel0_21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jLabel0_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel0_25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel0_14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel0_18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel0_23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel0_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel0_12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jLabel0_17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel0_22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel0_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, snackSlots_jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel0_16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel0_15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(title_Label1)
                                                .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(15, 15, 15)
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(10, 10, 10)
                                        .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel0_20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                                    .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel0_9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel0_13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel0_19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel0_24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        snackSlots_jPanel1Layout.setVerticalGroup(
            snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(snackSlots_jPanel1Layout.createSequentialGroup()
                .addComponent(title_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel0_0)
                    .addComponent(jLabel0_2)
                    .addComponent(jLabel0_16)
                    .addComponent(jLabel0_15)
                    .addComponent(jLabel0_20))
                .addGap(18, 18, 18)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)))
                .addGap(5, 5, 5)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_0)
                    .addComponent(jLabel0_11)
                    .addComponent(jLabel0_1)
                    .addComponent(jLabel0_26)
                    .addComponent(jLabel0_21))
                .addGap(18, 18, 18)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel0_6)
                    .addComponent(jLabel0_4)
                    .addComponent(jLabel0_12)
                    .addComponent(jLabel0_17)
                    .addComponent(jLabel0_22))
                .addGap(18, 18, 18)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(2, 2, 2)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel0_9)
                    .addComponent(jLabel0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel0_13)
                    .addComponent(jLabel0_19)
                    .addComponent(jLabel0_24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(snackSlots_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel0_7)
                    .addComponent(jLabel0_25)
                    .addComponent(jLabel0_14)
                    .addComponent(jLabel0_18)
                    .addComponent(jLabel0_23)))
        );

        jLabel0_13.getAccessibleContext().setAccessibleName("ID: 18");

        jLabel_error.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel_error.setForeground(java.awt.Color.red);
        jLabel_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1_ErrorMessageLayout = new javax.swing.GroupLayout(jPanel1_ErrorMessage);
        jPanel1_ErrorMessage.setLayout(jPanel1_ErrorMessageLayout);
        jPanel1_ErrorMessageLayout.setHorizontalGroup(
            jPanel1_ErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_ErrorMessageLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_ErrorMessageLayout.setVerticalGroup(
            jPanel1_ErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_ErrorMessageLayout.createSequentialGroup()
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel_error.getAccessibleContext().setAccessibleName(" INVALID KEY PAID ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moneySlot_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyPaid_jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1_ErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(snackSlots_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1_ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moneySlot_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyPaid_jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(snackSlots_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyPaid_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyPaid_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyPaid_jTextFieldActionPerformed

    private void coin_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coin_jTextFieldActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        // Key Paid Add Number "8" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"8");
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        // Key Paid Add Number "6" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"6");
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        // Key Paid Add Number "9" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"9");
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
       // Key Paid Add Number "5" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"5");
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        // Key Paid Add Number "4" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"4");
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        // Key Paid Add Number "3" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"3");
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        //Key Paid Add Number "7" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"7");
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        // Key Paid Add Number "2" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"2");
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // Key Paid Add Number "1" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"1");
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // This function to clear keypaid
        keyPaid_jTextField.setText("");
        jLabel_error.setText("");
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void change_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_jButton2ActionPerformed
        // This function to reset Cost to zero
        /*
            TODO1: Set Money poket =0.00 
            coin_jTextField.setText("$ "+moneyPoket);
        */
        this.snackMachine.setChanges(0.00);
        coin_jTextField.setText("$ "+"0.00");
       
    }//GEN-LAST:event_change_jButton2ActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // Cancel Purshiased 
        System.exit(0);
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_20cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_20cActionPerformed
           // Add 0.20 to change coins panel ...
        if (this.snackMachine.getChanges()>= 0.00){
          double currentChange=this.snackMachine.getChanges();
          currentChange+= 0.20;
          currentChange =Double.parseDouble(new DecimalFormat("##.##").format(currentChange));
          this.snackMachine.setChanges(currentChange);
          this.coin_jTextField.setText("$ "+currentChange);
        }
    }//GEN-LAST:event_jButton_20cActionPerformed

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        //Key Paid Add Number "0" to the screen 
        keyPaid_jTextField.setText(keyPaid_jTextField.getText()+"0");
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_10cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_10cActionPerformed
        // Add 0.10 to change coins panel ...
        if (this.snackMachine.getChanges()>= 0.00){
          double currentChange=this.snackMachine.getChanges();
          currentChange+= 0.10;
          currentChange =Double.parseDouble(new DecimalFormat("##.##").format(currentChange));
          this.snackMachine.setChanges(currentChange);
          this.coin_jTextField.setText("$ "+currentChange);
        }
          
    }//GEN-LAST:event_jButton_10cActionPerformed

    private void jButton_50cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_50cActionPerformed
           // Add 0.50 to change coins panel ...
        if (this.snackMachine.getChanges()>= 0.00){
          double currentChange=this.snackMachine.getChanges();
          currentChange+= 0.50;
          currentChange =Double.parseDouble(new DecimalFormat("##.##").format(currentChange));
          this.snackMachine.setChanges(currentChange);
          this.coin_jTextField.setText("$ "+currentChange);
        }
    }//GEN-LAST:event_jButton_50cActionPerformed

    private void jButton_1$ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1$ActionPerformed
           // Add 1.00 to change coins panel ...
        if (this.snackMachine.getChanges()>= 0.00){
          double currentChange=this.snackMachine.getChanges();
          currentChange+= 1.00;
          currentChange =Double.parseDouble(new DecimalFormat("##.##").format(currentChange));
          this.snackMachine.setChanges(currentChange);
          this.coin_jTextField.setText("$ "+currentChange);
        }
    }//GEN-LAST:event_jButton_1$ActionPerformed

    private void jButton_20$ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_20$ActionPerformed
           // Add 20 to change coins panel ...
        if (this.snackMachine.getChanges()>= 0.00){
          double currentChange=this.snackMachine.getChanges();
          currentChange+= 20;
          currentChange =Double.parseDouble(new DecimalFormat("##.##").format(currentChange));
          this.snackMachine.setChanges(currentChange);
          this.coin_jTextField.setText("$ "+currentChange);
        }
    }//GEN-LAST:event_jButton_20$ActionPerformed

    private void jButton_50$ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_50$ActionPerformed
           // Add 50 to change coins panel ...
         if (this.snackMachine.getChanges()>= 0.00){
          double currentChange=this.snackMachine.getChanges();
          currentChange+= 50;
          currentChange =Double.parseDouble(new DecimalFormat("##.##").format(currentChange));
          this.snackMachine.setChanges(currentChange);
          this.coin_jTextField.setText("$ "+currentChange);
         }
    }//GEN-LAST:event_jButton_50$ActionPerformed

    private void ok_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_jButton3ActionPerformed
        // Purchased Item 
        if (keyPaid_jTextField.getText().length()>2){
            jLabel_error.setText("INVALID KEY PAID");
        }else{
            String message = this.snackMachine.purchased(keyPaid_jTextField.getText());
            if (message.equals("SUCCESSFUL BUYING")){
                 double currentChange =Double.parseDouble(new 
                 DecimalFormat("##.##").format(this.snackMachine.getChanges()));
                 
                 this.snackMachine.setChanges(currentChange);
                 coin_jTextField.setText("$ "+currentChange);
                 jLabel_error.setText("SUCCESSFUL BUYING");
            }else{
                 jLabel_error.setText(message);
        }
        }
        
       
        
        
    }//GEN-LAST:event_ok_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new JFrameVendingMachine().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_jButton2;
    private javax.swing.JTextField coin_jTextField;
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_1$;
    private javax.swing.JButton jButton_10c;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_20$;
    private javax.swing.JButton jButton_20c;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_50$;
    private javax.swing.JButton jButton_50c;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JLabel jLabel0_0;
    private javax.swing.JLabel jLabel0_1;
    private javax.swing.JLabel jLabel0_11;
    private javax.swing.JLabel jLabel0_12;
    private javax.swing.JLabel jLabel0_13;
    private javax.swing.JLabel jLabel0_14;
    private javax.swing.JLabel jLabel0_15;
    private javax.swing.JLabel jLabel0_16;
    private javax.swing.JLabel jLabel0_17;
    private javax.swing.JLabel jLabel0_18;
    private javax.swing.JLabel jLabel0_19;
    private javax.swing.JLabel jLabel0_2;
    private javax.swing.JLabel jLabel0_20;
    private javax.swing.JLabel jLabel0_21;
    private javax.swing.JLabel jLabel0_22;
    private javax.swing.JLabel jLabel0_23;
    private javax.swing.JLabel jLabel0_24;
    private javax.swing.JLabel jLabel0_25;
    private javax.swing.JLabel jLabel0_26;
    private javax.swing.JLabel jLabel0_4;
    private javax.swing.JLabel jLabel0_5;
    private javax.swing.JLabel jLabel0_6;
    private javax.swing.JLabel jLabel0_7;
    private javax.swing.JLabel jLabel0_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1_0;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JPanel jPanel1_ErrorMessage;
    private javax.swing.JPanel keyPaid_jPanel2;
    private javax.swing.JTextField keyPaid_jTextField;
    private javax.swing.JPanel moneySlot_jPanel;
    private javax.swing.JButton ok_jButton3;
    private javax.swing.JPanel snackSlots_jPanel1;
    private javax.swing.JLabel title_Label1;
    // End of variables declaration//GEN-END:variables
}
